mod embedding;

pub use embedding::embedding;

// CUDA kernels generated by build.rs.
// https://github.com/huggingface/candle/blob/main/candle-examples/build.rs
#[cfg(feature = "cuda")]
pub(crate) mod cuda_kernels {
    include!(concat!(env!("OUT_DIR"), "/cuda_kernels.rs"));
}
