mod crelu;
mod screlu;

pub use crelu::crelu;
pub use screlu::screlu;

// CUDA kernels generated by build.rs which must be included
// https://github.com/huggingface/candle/blob/main/candle-examples/build.rs
#[cfg(feature = "cuda")]
pub(crate) mod cuda_kernels {
    include!(concat!(env!("OUT_DIR"), "/cuda_kernels.rs"));
}
