[package]
name = "search"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }
repository = { workspace = true }

[features]
tuning = ["config/tuning"]

[dependencies]
config = { path = "../config" }
nnue = { path = "../nnue" }
uci = { path = "../uci" }
utils = { path = "../utils" }

arrayvec = { workspace = true }
cozy-chess = { workspace = true }
ahash = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
pyrrhic-rs = "0.2"

[lib]
name = "search"

[lints]
workspace = true
