[package]
name = "grail"
description = "A UCI chess engine written in Rust"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
config = { path = "../config" }
search = { path = "../search" }
nnue = { path = "../nnue" }
uci = { path = "../uci" }

ahash = { workspace = true }
cozy-chess = { workspace = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }

[lints]
workspace = true
