[package]
name = "nnue"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }
repository = { workspace = true }

[dependencies]
utils = { path = "../utils" }

cozy-chess = { workspace = true }
log = { workspace = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }

[build-dependencies]
cudaforge = { version = "0.1.2", optional = true }

[features]
default = []
cuda = [
    "candle-core/cuda",
    "candle-nn/cuda",
    "dep:cudaforge",
]
metal = [
    "candle-core/metal",
    "candle-nn/metal",
]

[lib]
name = "nnue"

[[bin]]
name = "nnue-analysis"
path = "src/bin/analysis/main.rs"

[lints]
workspace = true
