[package]
name = "utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }
repository = { workspace = true }

[dependencies]
cozy-chess = { workspace = true }
rand = { workspace = true }

[target.'cfg(all(any(target_arch = "x86", target_arch = "x86_64"), target_feature = "bmi2"))'.dependencies]
cozy-chess = { workspace = true, features = ["pext"] }

[lints]
workspace = true
