[package]
name = "tuning"
description = "SPSA tuning for Grail"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
clap = { workspace = true }
num_cpus = { workspace = true }

[[bin]]
name = "tuner"
path = "src/bin/tuner/main.rs"

[lints]
workspace = true
